**What are defer, panic and recover? How do you recover from a run-timepanic?**

`defer` is a special Go statement used to schedule a function call to be run after the function completes (very much like `finally` in Python). For example:

```go
package main

import "fmt"

func first() {
     fmt.Println("1st")
}
func second() {
     fmt.Println("2nd")
}
func main() {
     defer second()
     first()
}
```
This program prints `1st` followed by `2nd`. Basically, `defer` moves the call to `second` to the end of the function.

`panic` cause a run time error. We can handle a run-time panic with the built-in `recover` function. `recover` stops the panic and returns the value that was passed to the call to `panic`. For instance:

```go
package main

import "fmt"

func main() {
     defer func() {
     	   str := recover()
	   fmt.Println(str)
     } ()
     panic("PANICKING!")
}
```
Note the `()` after `defer`, that's a function call. `defer` works with a called function only.